-- Complete data load for 9 skill probability curves
-- This file will be generated by parsing the CSV files
-- Total expected records: ~22,500 (9 skills × 25 ages × 100 percentiles)

-- Skill mapping:
-- 2 = Secure Attachment
-- 3 = Babbling
-- 6 = Sensory Development
-- 7 = Object Exploration
-- 8 = Coordination
-- 12 = Head Control
-- 17 = Memory and Attention
-- 19 = Newborn Reflexes and Posture
-- 22 = Foundations of Social Development

-- NOTE: Due to file size limitations, the complete INSERT statements
-- will be executed programmatically via supabase--insert tool
-- This file serves as documentation

-- Sample format:
-- INSERT INTO skill_percentile_curves (skill_id, skill_name, age_months, percentile, probability, locale) VALUES
-- (7, 'Object Exploration', 0, 0.01, 0.0800, 'en'),
-- (7, 'Object Exploration', 0, 0.02, 0.0800, 'en'),
-- ... continues for 22,500 total records
